src/objects/FieloPLT__Transaction__c.object
<CustomObject>
    <description>Actions that grant Points, Badges o Rewards to Members in exchange of a specific actions performed</description>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Member that generated the Transaction.</description>
        <inlineHelpText>Enter the Member who generated the Transaction.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Amount__c</fullName>
        <label>Amount</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Date__c</fullName>
        <label>Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Distributor__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Distributor</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>HasDetails__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Details</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>InvoiceNumber__c</fullName>
        <label>Invoice Number</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Member__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Invoices</relationshipLabel>
        <relationshipName>Invoices</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Invoice Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/Invoices.cls
public with sharing class Invoices extends SObjectDomain {
	
	public static Set<Id> processedIds = new Set<Id>();
    public static Boolean validateAdminFields = true;
    public static Decimal newAmount;
    public static Decimal oldAmount;
    public static String newStatus;
    public static String oldStatus;
    public static String newDate;
    public static String oldDate;
    public static String newInvoiceNumber;
    public static String oldInvoiceNumber;
    public static Boolean amountHasChanged;
    public static Boolean dateHasChanged;
    public static Boolean invoiceNumberHasChanged;

    public Invoices(List<Invoice__c> records) {
        super(records);
    }

    public override void onAfterInsert() {
        FieloPLT.SObjectService.processRecords((List<Invoice__c>) Records, null);
    }

    public override void onValidate(){
        if(validateAdminFields){
            Set<Id> memberIds = new Set<Id>();
            for(Invoice__c invoice: (List<Invoice__c>)records){
                if(invoice.Member__c!=null)
                    memberIds.add(invoice.Member__c);
            }

            Map<Id,FieloPLT__Member__c> disabledUpdateMembers = new Map<Id, FieloPLT__Member__c>( new MembersSelector().selectByIdAndProgramWithDetailedInvoiceFalse(memberIds));

            for(Invoice__c invoice: (List<Invoice__c>)records){
                if( invoice.Amount__c != null && invoice.Amount__c != 0.0 )
                    if(invoice.Member__c!=null)
                        if( !disabledUpdateMembers.containsKey( invoice.Member__c ) )
                            invoice.addError( Label.AmountUpdateDisabled );
                if( invoice.Date__c == null ) {
                    invoice.addError( Label.DateFieldNull );
                } else if ( invoice.Date__c > System.today() ){
                    invoice.addError( Label.FutureDateField );
                }
            }
            getDuplicatedRecords(records);
        }
    }

    public override void onValidate( Map<Id,SObject> existingRecords ){
        if(validateAdminFields){
            Map<Id,Invoice__c> disabledUpdateinvoices = new Map<Id, Invoice__c>( new InvoicesSelector().selectByItemIdWithDetailedInvoiceDisabled(new Map<Id,Invoice__c>((List<Invoice__c>)records).keyset()));

            for(Invoice__c invoice: (List<Invoice__c>)records){
                newAmount = invoice.Amount__c!=null ? invoice.Amount__c : 0.0;
                oldAmount = ((Invoice__c)existingRecords.get(invoice.Id)).Amount__c!=null ? ((Invoice__c)existingRecords.get(invoice.Id)).Amount__c : 0.0;

                newDate = invoice.Date__c!=null ? String.valueOf(invoice.Date__c): '';
                oldDate = ((Invoice__c)existingRecords.get(invoice.Id)).Date__c!=null ? String.valueOf(((Invoice__c)existingRecords.get(invoice.Id)).Date__c) : '';

                newInvoiceNumber = invoice.InvoiceNumber__c != null ? invoice.InvoiceNumber__c : '';
                oldInvoiceNumber = ((Invoice__c)existingRecords.get(invoice.Id)).InvoiceNumber__c != null ? ((Invoice__c)existingRecords.get(invoice.Id)).InvoiceNumber__c : '';

                amountHasChanged = newAmount != oldAmount;
                dateHasChanged = newDate != oldDate;
                invoiceNumberHasChanged = newInvoiceNumber != oldInvoiceNumber;

                if( newAmount.setScale(2) != oldAmount.setScale(2) )
                    if( !disabledUpdateinvoices.containsKey( invoice.Id ) )
                        invoice.addError( Label.AmountUpdateDisabled );

                if( invoice.HasDetails__c != ((Invoice__c)existingRecords.get(invoice.Id)).HasDetails__c )
                    invoice.addError( Label.HasDetailsNotEditable );

                if( ((Invoice__c)existingRecords.get(invoice.Id)).Status__c != 'Open' ){
                    if( amountHasChanged || dateHasChanged || invoiceNumberHasChanged )
                        invoice.addError( Label.DraftNotEditable );
                }

                if( invoice.Date__c == null ) {
                    invoice.addError( Label.DateFieldNull );
                } else if ( invoice.Date__c > System.today() ){
                    invoice.addError( Label.FutureDateField );
                }

                if( !invoice.HasDetails__c &&
                    newAmount == 0.0 &&
                    invoice.Status__c != 'Open' &&
                    invoice.Status__c != 'New') {
                    invoice.addError( Label.ZeroAmount );
                }
            }
            getDuplicatedRecords(records);
        }
    }

    public override void onAfterUpdate(Map<Id,SObject> existingRecords) {
        List<Invoice__c> recordsToProcess = new List<Invoice__c>();
        Map<Id,Invoice__c> mapExistingRecordsToProcess = new Map<Id,Invoice__c>();
        Set<Id> recordsToRevert = new Set<Id>();

        for(Invoice__c record : (List<Invoice__c>)records){
            if(!processedIds.contains(record.Id)){
                recordsToProcess.add(record);
                mapExistingRecordsToProcess.put(record.Id,(Invoice__c)existingRecords.get(record.Id));
                processedIds.add(record.Id);
            }

            newStatus = record.Status__c;
            oldStatus = ((Invoice__c)existingRecords.get(record.Id)).Status__c;

            if(oldStatus == 'Approved' && newStatus == 'Canceled'){
                recordsToRevert.add(record.Id);
            }
        }
        if(!recordsToProcess.isEmpty()){
            FieloPLT.SObjectService.processRecords(recordsToProcess, mapExistingRecordsToProcess);
        }
        if(!recordsToRevert.isEmpty()){
            revertInvoices(recordsToRevert);
        }
    }

    public override void onApplyDefaults() {
        Set<Id> memberIds = new Set<Id>();
        for(Invoice__c invoice: (List<Invoice__c>)records){
            memberIds.add(invoice.Member__c);
        }

        Map<Id,FieloPLT__Member__c> detailessInvoiceMembers = new Map<Id, FieloPLT__Member__c>( new MembersSelector().selectByIdAndProgramWithDetailedInvoiceFalse(memberIds));

        for(Invoice__c record : (List<Invoice__c>)records){
            if(record.Status__c == null){
                record.Status__c = 'Open';
            }

            record.HasDetails__c = !detailessInvoiceMembers.containsKey( record.Member__c );
        }
    }

    public class Constructor implements SObjectDomain.IConstructable {
        public SObjectDomain construct(List<SObject> sObjectList) {            
            return new Invoices(sObjectList);
        }
    }

    public override void onBeforeDelete(){
        deleteInvoiceItems((List<Invoice__c>) Records);
    }

    public static void deleteInvoiceItems(List<Invoice__c> invoices){
        try{
            delete [SELECT Id FROM InvoiceItem__c WHERE Invoice__c IN : invoices];
        }
        catch(Exception e){
            for(Invoice__c invoice: invoices){
                invoice.addError(e.getMessage());
            }
        }
    }

    public static void revertInvoices(Set<Id> invoiceIds){
        List<Id> idsToRevert = new List<Id>(new Map<Id,FieloPLT__Transaction__c>(new TransactionsSelector().selectByInvoiceIdAndNotReverted(invoiceIds)).keySet());
        if(!idsToRevert.isEmpty())
            FieloPLT.TransactionService.revertTransactions( idsToRevert );
    }

    public static void getDuplicatedRecords(List<Invoice__c> invoices) {
        Set<String> invoiceNumbers = new Set<String>();
        Set<String> distributors = new Set<String>();
        for(Invoice__c invoice: invoices) {
            invoiceNumbers.add(invoice.InvoiceNumber__c);
            distributors.add(invoice.Distributor__c);
        }
        List<Invoice__c> existingInvoices = new InvoicesSelector().selectByInvoiceNumberDistributorAndStatus(
            invoiceNumbers, 
            distributors,
            'Approved');
        Map<String,Id> invoiceKeys = new Map<String,Id>();
        String key;
        for(Invoice__c existingInvoice: existingInvoices) {
            key = existingInvoice.Distributor__c != null ?
                existingInvoice.Distributor__c :
                '000000000000000000';
            key = existingInvoice.InvoiceNumber__c != null ?
                existingInvoice.InvoiceNumber__c :
                '-';
            invoiceKeys.put(
                key,
                existingInvoice.Id
            );
        }
        for(Invoice__c invoice: invoices) {
            if (invoiceKeys != null) {
                key = invoice.Distributor__c != null ?
                    invoice.Distributor__c :
                    '000000000000000000';
                key = invoice.InvoiceNumber__c != '' &&
                    invoice.InvoiceNumber__c != null ?
                    invoice.InvoiceNumber__c :
                    '-';
                if (invoiceKeys.containsKey(key)) {
                    if( invoice.Id == null ) {
                        invoice.addError( Label.DuplicatedInvoiceRecord );
                    } else if (invoiceKeys.get(key) != invoice.Id) {
                        invoice.addError( Label.DuplicatedInvoiceRecord );
                    }
                }    
            }
        }
    }
}