src/objects/FieloPLT__Program__c.object
<CustomObject>
    <description>Programs establish the general operation settings of your loyalty program.</description>
    <label>Program</label>
    <nameField>
        <label>Program Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Programs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/FieloPLT__Transaction__c.object
<CustomObject>
    <description>Actions that grant Points, Badges o Rewards to Members in exchange of a specific actions performed</description>
    <fields>
        <fullName>FieloPLT__IsOffline__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Transaction is processed offline.</description>
        <inlineHelpText>When ticked, Transaction is processed offline.</inlineHelpText>
        <label>Offline</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsProcessed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It shows if Transaction was processed.</description>
        <inlineHelpText>When ticked, the Transaction was processed.</inlineHelpText>
        <label>Processed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It shows if Transaction was reverted.</description>
        <inlineHelpText>When ticked, Transaction was reverted.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Member__c</fullName>
        <deleteConstraint>Restrict</deleteConstraint>
        <description>Member that generated the Transaction.</description>
        <inlineHelpText>Enter the Member who generated the Transaction.</inlineHelpText>
        <label>Member</label>
        <referenceTo>FieloPLT__Member__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <required>true</required>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Points__c</fullName>
        <description>Transaction Points.</description>
        <inlineHelpText>Enter the number of Transaction Points.</inlineHelpText>
        <label>Points</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FieloPLT__SkipEngine__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Automatically completed when a Reverted Transaction is chosen.</description>
        <inlineHelpText>When ticked, Rule Engine is skipped and Member obtains the Transaction Points.</inlineHelpText>
        <label>Skip Engine</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Pending for Approval</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Approved</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Rejected</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Canceled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New</fullName>
            </picklistValues>
            <restrictedPicklist>true</restrictedPicklist>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>Invoice__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Invoice</label>
        <referenceTo>Invoice__c</referenceTo>
        <relationshipLabel>Invoice Items</relationshipLabel>
        <relationshipName>InvoiceItems</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Invoice Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestChangeInvoiceStatus.cls
@isTest
public class TestChangeInvoiceStatus {
    private static List<FieloPLT__Program__c> programs;
    private static List<FieloPLT__Member__c> members;
    private static List<FieloPRP__Invoice__c> invoices;
    private static FieloPLT__PointType__c pointType;
    private static FieloPLT__ProgramPointType__c programPointType;

    /*  TEST-1594
        Change Invoice Status
        – Approve a Pending Invoice (OK)
    */
    @testSetup static void createData(){
        //Given
        pointType = new FieloPLT__PointType__c(
            Name = 'Point', 
            FieloPLT__MemberBalanceField__c = 'FieloPLT__Points__c', 
            FieloPLT__TransactionBalanceField__c = 'FieloPLT__Points__c', 
            FieloPLT__RewardBalanceField__c = 'FieloPLT__Points__c', 
            FieloPLT__RedemptionBalanceField__c = 'FieloPLT__Points__c', 
            FieloPLT__RedemptionItemBalanceField__c = 'FieloPLT__Points__c'
        );
        insert pointType;

        programs = MockUpFactory.createPrograms('Default', 1);
        programs[0].FieloPRP__DetailedInvoice__c = true;
        insert programs;

        programPointType = new FieloPLT__ProgramPointType__c(
            FieloPLT__AuditPoints__c=false,
            FieloPLT__ExpirationMode__c='Total',
            FieloPLT__PointType__c=pointType.Id,
            FieloPLT__Program__c=programs[0].Id,
            FieloPLT__RequestPointApproval__c=false
        );
        insert programPointType;

        members = MockUpFactory.createMembers(programs[0].Id,2);
        insert members;

        //cannot insert member with points, member applydefaults ignores the points value upon insert
        members[0].FieloPLT__Points__c = 100;
        members[1].FieloPLT__Points__c = 100;
        update members;

        invoices = MockUpFactory.createInvoices(members[0].Id,1);
        insert invoices;

        InvoiceItem__c item = new InvoiceItem__c(
            Invoice__c = invoices[0].Id,
            Quantity__c = 10.0,
            TotalPrice__c = 70.0
        );
        
        insert item;

        FieloPLT__Transaction__c transaccion = new FieloPLT__Transaction__c(
            FieloPLT__Member__c = members.get(0).Id
            , FieloPRP__Invoice__c = invoices[0].Id
            , FieloPLT__Points__c = 100
            , FieloPLT__IsOffline__c = false
            , FieloPLT__IsProcessed__c = true
            , FieloPLT__SkipEngine__c = true
        );

        insert transaccion;
    }

    @isTest static void PRP_0004_FB(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Approved';

        update invoices;

        system.assertEquals('Approved', ((Invoice__c)[SELECT Id, Status__c FROM Invoice__c]).Status__c);

        Test.stopTest();
    }

    /*  TEST-1595
        Change Invoice Status
        – Reject a Pending Invoice (OK)
    */
    @isTest static void PRP_0004_FA1_1(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Rejected';

        update invoices;

        system.assertEquals('Rejected', ((Invoice__c)[SELECT Id, Status__c FROM Invoice__c]).Status__c);

        Test.stopTest();
    }

    /*  TEST-1596
        Change Invoice Status
        – Validations
        - Revert a Pending Invoice (NOK)
    */
    @isTest static void PRP_0004_FA1_2(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Reverted';

        try{
            update invoices;
        }
        catch(Exception e){
            //do nothing, expected validation
        }   

        system.assertEquals('Pending', ((Invoice__c)[SELECT Id, Status__c FROM Invoice__c]).Status__c);

        Test.stopTest();
    }

    /*  TEST-1597
        Change Invoice Status
        - Revert an Approved Invoice (OK)
    */
    @isTest static void PRP_0004_FA2(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Approved';

        update invoices;

        invoices[0].Status__c = 'Reverted';

        update invoices;

        system.assertEquals(true,[Select Id, Name, FieloPLT__IsReverted__c From FieloPLT__Transaction__c WHERE Invoice__c =: invoices[0].Id ].FieloPLT__IsReverted__c);
        system.assertEquals('Reverted',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1598
        Change Invoice Status
        - Review an Approved Invoice (OK)
    */
    @isTest static void PRP_0004_FA3_1(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Approved';

        update invoices;

        invoices[0].Status__c = 'Pending';

        update invoices;

        system.assertEquals(true,[Select Id, Name, FieloPLT__IsReverted__c From FieloPLT__Transaction__c WHERE Invoice__c =: invoices[0].Id ].FieloPLT__IsReverted__c);
        system.assertEquals('Pending',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1599
        Change Invoice Status
        – Validations
        - Reject an Approved Invoice (NOK)
    */
    @isTest static void PRP_0004_FA3_2(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Approved';

        update invoices;

        invoices[0].Status__c = 'Rejected';

        try{
            update invoices;
        }
        catch(Exception e){}

        system.assertEquals(false,[Select Id, Name, FieloPLT__IsReverted__c From FieloPLT__Transaction__c WHERE Invoice__c =: invoices[0].Id ].FieloPLT__IsReverted__c);
        system.assertEquals('Approved',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1600
        Change Invoice Status
        - Review a Rejected Invoice (OK)
    */
    @isTest static void PRP_0004_FA4_1(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Rejected';

        update invoices;

        invoices[0].Status__c = 'Pending';

        update invoices;
        
        system.assertEquals('Pending',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1601
        Change Invoice Status
        – Validations
        - Approve a Rejected Invoice (NOK)
    */
    @isTest static void PRP_0004_FA4_2(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Rejected';

        update invoices;

        invoices[0].Status__c = 'Approved';

        try{
            update invoices;
        }
        catch(Exception e){}
        
        system.assertEquals('Rejected',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1602
        Change Invoice Status
        – Validations
        - Revert a Rejected Invoice (NOK)
    */
    @isTest static void PRP_0004_FA4_3(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        Test.startTest();

        invoices[0].Status__c = 'Rejected';

        update invoices;

        invoices[0].Status__c = 'Reverted';

        try{
            update invoices;
        }
        catch(Exception e){}
        
        system.assertEquals('Rejected',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1603
        Change Invoice Status
        - Review a Reverted Invoice (OK)
    */
    @isTest static void PRP_0004_FA5_1(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        invoices[0].Status__c = 'Approved';

        update invoices;

        Test.startTest();

        invoices[0].Status__c = 'Reverted';

        update invoices;

        invoices[0].Status__c = 'Pending';

        update invoices;
                
        system.assertEquals('Pending',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1604
        Change Invoice Status
        – Validations
        - Reject a Reverted Invoice (NOK)
    */
    @isTest static void PRP_0004_FA5_2(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        invoices[0].Status__c = 'Approved';

        update invoices;

        Test.startTest();

        invoices[0].Status__c = 'Reverted';

        update invoices;

        invoices[0].Status__c = 'Rejected';

        try{
            update invoices;
        }
        catch(Exception e){}
                
        system.assertEquals('Reverted',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }

    /*  TEST-1605
        Change Invoice Status
        – Validations
        - Approve a Reverted Invoice (NOK)
    */
    @isTest static void PRP_0004_FA5_3(){
        invoices = [SELECT Id, Name, Status__c FROM Invoice__c];

        invoices[0].Status__c = 'Approved';

        update invoices;

        Test.startTest();

        invoices[0].Status__c = 'Reverted';

        update invoices;

        invoices[0].Status__c = 'Approved';

        try{
            update invoices;
        }
        catch(Exception e){}
                
        system.assertEquals('Reverted',[SELECT Id, Status__c FROM Invoice__c LIMIT 1].Status__c);

        Test.stopTest();
    }
}