src/objects/FieloPLT__Transaction__c.object
<CustomObject>
    <description>Actions that grant Points, Badges o Rewards to Members in exchange of a specific actions performed</description>
    <fields>
        <fullName>FieloPLT__Action__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Automatically generated related Action.</description>
        <inlineHelpText>Related Action.</inlineHelpText>
        <label>Action</label>
        <referenceTo>FieloPLT__Action__c</referenceTo>
        <relationshipLabel>Transactions</relationshipLabel>
        <relationshipName>Transactions</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FieloPLT__Date__c</fullName>
        <defaultValue>now()</defaultValue>
        <description>Transaction date and time.</description>
        <inlineHelpText>Choose Transaction date and time.</inlineHelpText>
        <label>Date &amp; Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FieloPLT__IsReverted__c</fullName>
        <defaultValue>false</defaultValue>
        <description>It shows if Transaction was reverted.</description>
        <inlineHelpText>When ticked, Transaction was reverted.</inlineHelpText>
        <label>Reverted</label>
        <type>Checkbox</type>
    </fields>
    <label>Transaction</label>
    <nameField>
        <displayFormat>T-{0000000}</displayFormat>
        <label>Transaction Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Transactions</pluralLabel>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/TransactionsSelector.cls
public class TransactionsSelector extends SObjectSelector{

	public List<Schema.SObjectField> getSObjectFieldList(){
		return new List<Schema.SObjectField> {
				FieloPLT__Transaction__c.Id,
				FieloPLT__Transaction__c.FieloPLT__Date__c,
				FieloPLT__Transaction__c.FieloPLT__Action__c,
                FieloPLT__Transaction__c.FieloPLT__IsReverted__c
			};
	}

	public TransactionsSelector(Set<String> fields){
		super(fields);
	}

	public TransactionsSelector(){
		super();
	}

	public Schema.SObjectType getSObjectType(){
		return FieloPLT__Transaction__c.sObjectType;
	}

	public List<FieloPLT__Transaction__c> selectById(Set<ID> idSet){
		return (List<FieloPLT__Transaction__c>) selectSObjectsById(idSet);
	}

    public List<FieloPLT__Transaction__c> selectByInvoiceIdAndNotReverted(Set<Id> invoiceIds ){
        return (List<FieloPLT__Transaction__c>) Database.query(
                String.format(
                'SELECT {0} ' +
                  'FROM {1} ' +
                  'WHERE FieloPRP__Invoice__c In : invoiceIds AND FieloPLT__IsReverted__c=false',
                new List<String> {
                    getFieldListString(),
                    getSObjectName()}));
    }
}