src/objects/Invoice__c.object
<CustomObject>
    <fields>
        <fullName>HasDetails__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Has Details</label>
        <type>Checkbox</type>
    </fields>
    <label>Invoice</label>
    <nameField>
        <displayFormat>I-{00000000}</displayFormat>
        <label>Invoice</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoices</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceViewController.cls
public class InvoiceViewController{
    public Invoice__c record {get;set;}
    private ApexPages.StandardController controller;
    public List<Attachment> images {get; set;}

    /**
    * @brief constructor
    */
    public InvoiceViewController(ApexPages.StandardController controller) {
        this.controller = controller;

        this.controller.addFields(new List<String>{'Name','HasDetails__c'});
        record = (Invoice__c)controller.getRecord();

        images = [SELECT Id, Name FROM Attachment WHERE ParentId =: record.Id];
    }

}