src/objects/InvoiceItem__c.object
<CustomObject>
    <fields>
        <fullName>Quantity__c</fullName>
        <label>Quantity</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>TotalPrice__c</fullName>
        <label>Total Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>UnitPrice__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <label>Invoice Item</label>
    <nameField>
        <displayFormat>IT-{00000000}</displayFormat>
        <label>Invoice Item</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/InvoiceItemsSelector.cls
public class InvoiceItemsSelector extends SObjectSelector{

    public List<Schema.SObjectField> getSObjectFieldList(){
        return new List<Schema.SObjectField> {
                InvoiceItem__c.Id,
                InvoiceItem__c.Name,
                InvoiceItem__c.Quantity__c,
                InvoiceItem__c.UnitPrice__c,
                InvoiceItem__c.TotalPrice__c
            };
    }

    public InvoiceItemsSelector(Set<String> fields){
        super(fields);
    }

    public InvoiceItemsSelector(){
        super();
    }

    public Schema.SObjectType getSObjectType(){
        return InvoiceItem__c.sObjectType;
    }

    public List<InvoiceItem__c> selectById(Set<Id> invoiceItemIds){
        return (List<InvoiceItem__c>) selectSObjectsById(invoiceItemIds);
    }

    public List<InvoiceItem__c> selectByIdWithInvoiceStatusPending(Set<Id> invoiceItemIds){
        String draftStatus = 'Pending';
        return (List<InvoiceItem__c>) Database.query(String.format(
                'select {0} ' +
                  'from {1} ' +
                  'where Id In: invoiceItemIds ' +
                  'and FieloPRP__Invoice__r.FieloPRP__Status__c = :draftStatus ' +
                  'order by {2}',
                new List<String> {
                    getFieldListString(),
                    getSObjectName(),
                    getOrderBy() } ));
    }
}